AITUDC/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', include('user.urls')),
    path('main/', include('main.urls')),
    path('api/', include('api.urls')),
    path('keytaker/', include('keytaker.urls')),
    path('keyreturner/', include('keyreturner.urls')),
    path('admin/', admin.site.urls),

    # path('login/', LoginView.as_view(), name='login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('getHistoryData/<int:page>/<int:step>/', views.getHistoryData, name='getHistoryData'),
    path('searchRoom/<str:room>/', views.searchRoom, name='searchRoom'),
    path('takeroom_isVar_changed/', views.takeroom_isVar_changed, name='takeroom_isVar_changed'),
    path('get_last5_orders/', views.get_last5_orders, name='get_last5_orders'),
    path('cancel-takeroom/<int:pk>', views.cancel_takeroom, name='cancel-takeroom'),
    path('get-room-schedule/<str:room_number>/', views.get_room_schedule, name='get_room_schedule'),
    path('create-reservation/<str:room_name>/<str:start_time_input>/<int:is_take>/', views.create_reservation, name='create_reservation'),
    path('booking-change-is-take/<str:key>/<int:is_take>/', views.booking_change_is_take, name='booking_change_is_take'),
    path('get_rooms_status/<str:floor>/', views.get_rooms_status, name='get_rooms_status')
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.homeMain, name='homeMain'),
    path('404/', views.not_foundMain, name='not_foundMain'),
    path('login/', views.loginMain, name='loginMain'),
    path('logout/', views.logoutMain, name='logoutMain'),
    path('pin/', views.pinLocked, name='pinLocked'),
    path('history/', views.historyMain, name='historyMain'),
    path('history/ajax/', views.history_ajax, name='history_ajax'),
    path('history/export/', views.export_history_to_excel, name='export_history_to_excel'),
    path('users/', views.usersMain, name='usersMain'),
    path('rooms/', views.roomsMain, name='roomsMain'),
    path('get_room_map/', views.get_room_map, name='get_room_map'),
    path('get_rooms_floor/', views.get_rooms_floor, name='get_rooms_floor'),
    path('settings/', views.settingsMain, name='settingsMain'),
    path('pinlock/<str:code>', views.PinLock, name='PinLock'),
    path('confirm-takeroom/<int:pk>', views.confirm_takeroom, name='confirm-takeroom'),
    path('cancel-takeroomMain/<int:pk>', views.cancel_takeroomMain, name='cancel-takeroomMain'),
    path('confirm-booking/<str:key>/', views.confirmBooking, name='confirm-booking'),
    path('qr/', views.websocketQR, name='websocketQR'),
    path('update-qr/', views.updateQR, name='updateQR'),
    path('schedule/', views.schedule_page, name='schedule_page')
   ]

keytaker/models.py
import datetime
from django.db import models
from user.models import *

Floors = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3')
]


class Room(models.Model):
    name = models.CharField(max_length=45)
    description = models.CharField(max_length=50, default="", blank=True, null=True)
    floor = models.CharField(max_length=2, choices=Floors, default='1')
    role = models.ManyToManyField(Role)
    is_occupied = models.BooleanField(default=False)
    is_visible = models.BooleanField(default=True)
    is_study_room = models.BooleanField(default=False)
    date = models.DateTimeField(blank=True, null=True)
    map_id = models.CharField(max_length=45,  blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Room'
        verbose_name_plural = 'Rooms'


class History(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, blank=True, null=True)
    fullname = models.CharField(max_length=50)
    role = models.ForeignKey(Role, on_delete=models.CASCADE, blank=True, null=True)
    is_verified = models.BooleanField(default=False)
    is_return = models.BooleanField(default=False)
    user = models.ForeignKey(MainUser, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.fullname

    class Meta:
        verbose_name = 'History'
        verbose_name_plural = 'History'


class Schedule(models.Model):
    DAYS_OF_WEEK = (
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
        (7, 'Sunday')
    )

    day = models.IntegerField(choices=DAYS_OF_WEEK)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()
    professor = models.ForeignKey(MainUser, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedule'


class StudyRoomSchedule(models.Model):
    STATUS_CHOICES = (
        ('inactive', 'Inactive'),
        ('lesson', 'Lesson'),
        ('free', 'Free'),
        ('reserved', 'Reserved'),
        ('busy', 'Busy'),
    )
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()
    professor = models.ForeignKey(MainUser, on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='inactive')

    class Meta:
        verbose_name = 'StudyRoom Schedule'
        verbose_name_plural = 'StudyRoom Schedule'


TypeTakeRoom = [
    ('QR', 'QR'),
    ('Manually', 'Manually')
]


class SettingsKeyTaker(models.Model):
    confirmation_code = models.CharField(max_length=100)
    code_timestamp = models.DateTimeField(blank=True, null=True)
    is_confirm = models.BooleanField(default=False)
    in_process = models.BooleanField(default=False)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, blank=True, null=True)
    type = models.CharField(default='Manually', max_length=10, choices=TypeTakeRoom)
    step = models.IntegerField(default=1)
    error = models.CharField(max_length=100, default='', blank=True, null=True)

    def __str__(self):
        return self.confirmation_code

    class Meta:
        verbose_name = 'Settings KeyTaker'
        verbose_name_plural = 'Settings KeyTaker'


class Orders(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    confirmation_code = models.CharField(max_length=100)
    note = models.CharField(max_length=100, default='', blank=True, null=True)
    user = models.ForeignKey(MainUser, on_delete=models.CASCADE)
    orders_timestamp = models.DateTimeField()
    is_available = models.BooleanField(default=True)
    is_confirm = models.BooleanField(default=False)

    def __str__(self):
        return self.confirmation_code

    class Meta:
        verbose_name = 'Orders'
        verbose_name_plural = 'Orders'


class Reservation(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    start_time = models.TimeField()
    key = models.CharField(max_length=32, blank=True)
    created_at = models.DateTimeField()
    is_take = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.key

main/models.py
from django.db import models


class PIN(models.Model):
    code = models.CharField(max_length=15, default='')
    is_locked = models.BooleanField(default=False)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'PIN code'
        verbose_name_plural = 'PIN code'

main/views.py
import asyncio
import json
import os
from datetime import datetime, timedelta
from zipfile import BadZipFile

import qrcode
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.contrib.postgres.aggregates import ArrayAgg
from django.core.exceptions import ValidationError
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.hashers import check_password
from django.views.decorators.http import require_GET

from AITUDC import settings
from api.views import confirmed_order, canceled_order
from keytaker.consumers import WebSocketQR
from keytaker.models import Orders, History, Room, Reservation, StudyRoomSchedule, Schedule
from django.contrib import messages
from django.utils import timezone

from django.core import serializers

from keytaker.views import check_room, create_empty_cells, clear_room_schedule, fill_room_schedule
from main.models import PIN
from user.models import MainUser, Role
import openpyxl
from openpyxl.styles import PatternFill
import pytz
from datetime import datetime
import pandas as pd
# import magic
from openpyxl import load_workbook

local_tz = pytz.timezone('Asia/Almaty')


def export_history_to_excel(request):
    # Get the queryset
    history_queryset = History.objects.all().order_by('-date')
    # Create a new workbook
    wb = openpyxl.Workbook()
    # Select the active worksheet
    ws = wb.active
    # Add headers to the worksheet
    ws['A1'] = 'Date'
    ws['B1'] = 'Fullname'
    ws['C1'] = 'Role'
    ws['D1'] = 'Room'
    ws['E1'] = 'Verified (QR)'
    ws['F1'] = 'Returned'
    # Loop over the queryset and add the data to the worksheet
    for i, entry in enumerate(history_queryset, start=2):
        ws.cell(row=i, column=1, value=entry.date.astimezone(local_tz).strftime('%d-%m-%Y %H:%M:%S'))
        ws.cell(row=i, column=2, value=entry.fullname)
        ws.cell(row=i, column=3, value=entry.role.name)
        ws.cell(row=i, column=4, value=entry.room.name)
        ws.cell(row=i, column=5, value='Yes' if entry.is_verified else 'No')
        ws.cell(row=i, column=6, value='Yes' if entry.is_return else 'No')
        # Set the background color of the row to red if is_return is True, green otherwise
        if entry.is_return:
            fill = PatternFill(start_color='C6EFCE', end_color='C6EFCE', fill_type='solid')
        else:
            fill = PatternFill(start_color='FFC7CE', end_color='FFC7CE', fill_type='solid')
        for cell in ws[i]:
            cell.fill = fill
    # Adjust the column width to fit the text
    for col in ws.columns:
        column = col[0].column_letter
        length = max(len(str(cell.value)) for cell in col)
        adjusted_width = (length + 2) * 1.2
        ws.column_dimensions[column].width = adjusted_width
    # Set the filename and the content-type of the response
    now = datetime.now()
    formatted_date = now.strftime('%d.%m.%Y')
    filename = 'history ' + formatted_date + '.xlsx'
    content_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    # Create a response object
    response = HttpResponse(content_type=content_type)
    # Set the content-disposition header
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    # Write the workbook to the response
    wb.save(response)
    # Return the response
    return response


def getOrders():
    last_orders = Orders.objects.filter(
        is_available=True,
        is_confirm=False,
        orders_timestamp__gte=timezone.now() - timezone.timedelta(minutes=5)
    ).order_by('orders_timestamp')

    orders_list = []
    for order in last_orders:
        orders_list.append({
            'id': order.id,
            'room': order.room.name,
            'note': order.note,
            'user': {
                'name': order.user.full_name,
                'email': order.user.email
            },
            "orders_timestamp": order.orders_timestamp.astimezone(local_tz).strftime("%H:%M:%S"),
            "is_confirm": order.is_confirm,
            "is_available": order.is_available
        })
    return orders_list


def not_foundMain(request):
    return render(request, 'notfound404Main.html')


@login_required(login_url='loginMain')
def homeMain(request):
    orders_list = getOrders()
    protocol = 'https' if request.is_secure() else 'http'
    link_confirm = f'{protocol}://{request.get_host()}/'
    print(link_confirm)
    img = qrcode.make(link_confirm)
    img.save("media/mobile.png")
    return render(request, 'home-main.html', {
        'orders_list': orders_list,
        'media_url': settings.MEDIA_URL
    })


@login_required(login_url='loginMain')
def settingsMain(request):
    if request.method == "POST":
        if not request.user.is_staff:
            messages.error(request, 'Access denied')
            return redirect('loginMain')
        if 'change_password' in request.POST:
            old_password = request.POST.get('old_password')
            new_password = request.POST.get('new_password')
            checkPassword = check_password(old_password, request.user.password)
            if checkPassword:
                user_obj = User.objects.get(username=request.user)
                user_obj.set_password(new_password)
                user_obj.save()
                messages.success(request, 'Password changed successfully. Please log in again.')
                return redirect('loginMain')
            else:
                messages.error(request, 'Неверный пароль')
                return redirect('settingsMain')
        elif 'create_ec' in request.POST:
            if not request.user.is_superuser:
                messages.success(request, 'Недостаточно прав для выполнения этой команды.')
                return redirect('settingsMain')
            create_empty_cells()
            messages.success(request, 'Empty cells for each room was successfully created.')
            return redirect('settingsMain')
        elif 'clear_rs' in request.POST:
            if not request.user.is_superuser:
                messages.success(request, 'Недостаточно прав для выполнения этой команды.')
                return redirect('settingsMain')
            clear_room_schedule()
            messages.success(request, 'Room schedule was successfully cleared.')
            return redirect('settingsMain')
        elif 'fill_rs' in request.POST:
            if not request.user.is_superuser:
                messages.success(request, 'Недостаточно прав для выполнения этой команды.')
                return redirect('settingsMain')
            fill_room_schedule()
            messages.success(request, 'Room schedule was successfully filled.')
            return redirect('settingsMain')
        elif 'upload_schedule' in request.POST:
            if not request.user.is_superuser:
                messages.success(request, 'Недостаточно прав для выполнения этой команды.')
                return redirect('settingsMain')
            file = request.FILES.get('schedule_file')

            if not file:
                messages.error(request, 'Файл не найден.')
                return redirect('settingsMain')
            try:
                try:
                    error = create_schedule_from_excel(file)
                except BadZipFile:
                    error = 'Файл не является допустимым форматом или поврежден'

                if error:
                    messages.error(request, error)
                    return redirect('settingsMain')
                messages.success(request, 'Расписание успешно создано.')
                return redirect('settingsMain')
            except ValidationError as e:
                messages.error(request, 'Ошибка создания расписания.')
                return redirect('settingsMain')
        elif 'add_users' in request.POST:
            if not request.user.is_superuser:
                messages.success(request, 'Недостаточно прав для выполнения этой команды.')
                return redirect('settingsMain')
            file = request.FILES.get('users_file')
            if not file:
                messages.error(request, 'Файл не найден.')
                return redirect('settingsMain')
            try:
                try:
                    error = create_schedule_from_excel(file)
                except BadZipFile:
                    error = 'Файл не является допустимым форматом или поврежден'

                if error:
                    messages.error(request, error)
                    return redirect('settingsMain')
                messages.success(request, 'Пользователи успешно добавлены.')
                return redirect('settingsMain')
            except ValidationError as e:
                messages.error(request, 'Ошибка добавления пользователей.')
                return redirect('settingsMain')

    orders_list = getOrders()
    return render(request, 'settings.html', {
        'orders_list': orders_list
    })


def create_schedule_from_excel(file):
    # Проверка расширения файла
    _, file_extension = os.path.splitext(file.name)
    if file_extension not in ['.xls', '.xlsx']:
        return "Неверное расширение файла. Пожалуйста, загрузите файл Excel."
    df = pd.read_excel(file, engine='openpyxl')

    # Проверка наличия столбцов
    required_columns = ['Room', 'week_day', 'professor/email', 'start_time', 'end_time']
    missing_columns = [column for column in required_columns if column not in df.columns]

    if missing_columns:
        # Если некоторые столбцы отсутствуют, генерируем ошибку
        error_message = f"Отсутствуют необходимые столбцы: {', '.join(missing_columns)}"
        return error_message

    # Очищаем старые данные в расписании
    Schedule.objects.all().delete()

    for index, row in df.iterrows():
        room_name = row['Room']
        week_day = row['week_day']

main/templates/confirm-takeroom-main.html
{% extends 'base.html' %}
{% block title %}Заявка #{{ order.id }}{% endblock %}
{% block content %}
    {% load static %}

    <div class="container-fluid">
        <div class="card shadow mb-5" style="margin-top: 15px;">
            <div class="card-header py-3">
                <p style="top: 1rem;right: 1rem;position: absolute;"> {{ order.orders_timestamp }}</p>
                <p class="text-primary m-0 fw-bold">Взятие ключа (Заявка #{{ order.id }})</p>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        {% if messages %}
                            {% for message in messages %}
                                <span class="badge bg-dark fs-6 mb-2"><svg xmlns="http://www.w3.org/2000/svg"
                                                                           width="1em"
                                                                           height="1em" fill="currentColor"
                                                                           viewBox="0 0 16 16"
                                                                           class="bi bi-exclamation-circle-fill"
                                                                           style="padding-bottom: 0px;margin-bottom: 0px;margin-top: -4px;">
                                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"></path>
                                </svg>&nbsp;{{ message }}</span>
                            {% endfor %}
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3"><label class="form-label" for="signature"><strong>Введите код
                                подтверждения (цифры):</strong></label>
                                <textarea style="width: 200px; font-size: 20px; resize: none;"
                                          class="form-control form-control-sm"
                                          id="signature" rows="1"
                                          name="code" oninput="validateInput(this)"></textarea></div>
                            <div class="mb-3">
                                <button class="btn btn-primary btn-sm" type="submit">Подтвердить</button>
                                <button id="cancelOrderPage" class="btn btn-danger btn-sm" style="margin-left: 10px;">
                                    Отклонить заявку
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6">
                        <form>
                            <div class="mb-3"><label class="form-label"
                                                     for="signature"><strong>Информация:</strong></label>
                                <div class="mb-3"><label class="form-label"
                                                         for="signature">
                                    <strong>ФИО: </strong>{{ order.user.name }} ({{ order.user.email }})<br>
                                    <strong>Комната:</strong> {{ order.room }}
                                    {% if order.note %}
                                        <br>Комментарий: {{ order.note }}</label>
                                    {% endif %}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
        document.getElementById('signature').addEventListener("keydown", function (event) {
            if (event.key === "Enter") {
                event.preventDefault();
            }
        });

        var button = document.getElementById("cancelOrderPage");
        if (button) {
            button.addEventListener("click", function () {
                url = location.protocol + "//" + location.host + "/main/cancel-takeroomMain/" +
                    {{ order.id }}
                    console.log(url)
                var xhr = new XMLHttpRequest();
                xhr.open('GET', url, true);
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
                        var response = JSON.parse(xhr.responseText);
                        console.log(response)
                    }
                };
                xhr.send();
            });
        }

        function validateInput(element) {
            element.value = element.value.replace(/\D/g, '');
        }
    </script>
{% endblock %}

main/templates/notfound404Main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <title>404 Page Not Found</title>
    <style>
        body {
            background-color: #ffffff;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            text-align: center;
        }

        h1 {
            font-size: 3rem;
            margin-bottom: 1rem;
            color: #333;
            display: inline-block;
            position: relative;
        }

        h1::after {
            content: '404';
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 25rem;
            color: #777;
            opacity: 0.3;
            z-index: -1;
        }

        h1 span {
            width: 1000px;
            display: block;
            position: relative;
            z-index: 1;
        }

        p {
            font-size: 1.2rem;
            color: #777;
            margin-bottom: 2rem;
        }

        a {
            color: #007bff;
            text-decoration: none;
        }

        @media (max-width: 480px) {
            h1 {
                font-size: 2.5rem;
            }

            h1::after {
                font-size: 15rem;
            }

            p {
                font-size: 1rem;
            }
        }
    </style>
</head>
<body>
<div>
    <h1><span>Not found</span></h1>
    <p>The page you are looking for does not exist.</p>
    <a href="{% url 'homeMain' %}">Go back to homepage</a>
</div>
</body>
</html>

main/templates/schedule.html
{% extends 'base.html' %}
{% block title %}Расписание{% endblock %}
{% block content %}
    {% load static %}

    <div class="container-fluid" style="margin-top: 20px;">
        <div class="card shadow">
            <div class="card-header py-3">
                <div class="d-flex justify-content-between align-items-center">
                    <p class="text-primary m-0 fw-bold">Расписание</p>
                    {% if request.user.is_superuser %}
                        <a class="btn btn-dark btn-sm ms-auto me-0" href="{% url 'settingsMain' %}">Сменить
                            расписание</a>
                    {% endif %}
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <form method="GET" action="{% url 'schedule_page' %}">
                        <p class="text m-0 fw-bold" style="margin-bottom: 10px !important;">Фильтры: </p>
                        <div class=" col-xl-4 text-nowrap">
                            <div id="dataTable_length" class="dataTables_length" aria-controls="dataTable">
                                <label class="form-label">Day:
                                    <select name="day" id="day-filter"
                                            class="d-inline-block form-select form-select-sm">
                                        <option value="1" {% if '1' in selected_days %}selected{% endif %}>Monday
                                        </option>
                                        <option value="2" {% if '2' in selected_days %}selected{% endif %}>Tuesday
                                        </option>
                                        <option value="3" {% if '3' in selected_days %}selected{% endif %}>Wednesday
                                        </option>
                                        <option value="4" {% if '4' in selected_days %}selected{% endif %}>Thursday
                                        </option>
                                        <option value="5" {% if '5' in selected_days %}selected{% endif %}>Friday
                                        </option>
                                        <option value="6" {% if '6' in selected_days %}selected{% endif %}>Saturday
                                        </option>
                                        <option value="7" {% if '7' in selected_days %}selected{% endif %}>Sunday
                                        </option>
                                    </select>
                                </label>
                            </div>
                        </div>
                        <div class=" col-xl-4 text-nowrap">
                            <div id="dataTable_length" class="dataTables_length" aria-controls="dataTable">
                                <label class="form-label">Room:
                                    <select name="room" id="room-filter"
                                            class="d-inline-block form-select form-select-sm">
                                        <option value="">All</option>
                                        {% for room in all_rooms %}
                                            <option value="{{ room.name }}"
                                                    {% if room.id|stringformat:'s' in selected_rooms %}selected{% endif %}>{{ room.name }}</option>
                                        {% endfor %}
                                    </select>
                                </label>
                            </div>
                        </div>
                        <div class=" col-xl-4 text-nowrap">
                            <div id="dataTable_length" class="dataTables_length" aria-controls="dataTable">
                                <label class="form-label">Professor:
                                    <select name="professor" id="professor-filter"
                                            class="d-inline-block form-select form-select-sm">
                                        <option value="">All</option>
                                        {% for professor in all_professors %}
                                            <option value="{{ professor.email }}"
                                                    {% if professor.id|stringformat:'s' in selected_professors %}selected{% endif %}>{{ professor.full_name }}
                                                ({{ professor.email }})
                                            </option>
                                        {% endfor %}
                                    </select>
                                </label>
                            </div>
                        </div>
                        <div class=" col-xl-3 text-nowrap">
                            <button class="btn btn-primary btn-sm" type="submit">Применить фильтры</button>
                        </div>
                    </form>
                </div>
                <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                    <table class="table my-0" id="dataTable">
                        <thead>
                        <tr>
                            <th>Day</th>
                            <th>Room</th>
                            <th>Professor</th>
                            <th>Start Time</th>
                            <th>End Time</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for schedule in schedules %}
                            <tr>
                                <td>{{ schedule.get_day_display }}</td>
                                <td>{{ schedule.room.name }}</td>
                                <td>{{ schedule.professor.user.username }}</td>
                                <td>{{ schedule.start_time|time:"H:i" }}</td>
                                <td>{{ schedule.end_time|time:"H:i" }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5" class="empty-row">No schedules found.</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}